### ISSUE TITLE
Error on GitLab CI

### ISSUE THREAD

**Issue by vojtasvoboda** [mwienk/docker-lftp#1]
Hello, I'm trying to run your Docker image on GitLabCI, but sometimes I'm getting this error causing build error:

```
Pulling docker image mwienk/docker-lftp:latest ...
ERROR: Preparation failed: Error: No such image: mwienk/docker-lftp:latest
Will be retried in 3s ...
```

Is there some another way/another image to get it works?

Thanks a lot in advice

**Comment by mwienk** [comment]
Seems like some kind of connection issue with docker hub and not really an issue with the image, so I'm closing this issue. If you use your own runners, try to pull the image manually on your cli.
